export const SEO_CONFIG = {
  siteName: 'Hope for the Hopeless Initiative',
  siteUrl: 'https://hopeforthehopeless.org',
  siteDescription: 'Restoring Hope, Transforming Lives - Humanitarian support, youth empowerment, and community development across Nigeria.',
  siteImage: '/images/og-image.jpg',
  twitterHandle: '@hopeforthehopeless',
  facebookPage: 'hopeforthehopeless',
  email: 'info@hopeforthehopeless.org',
  phone: '+234 123 456 7890',
  address: 'Abuja, Nigeria',

  pages: {
    home: {
      title: 'Home - Restoring Hope, Transforming Lives',
      description: 'Hope for the Hopeless Initiative provides humanitarian support, youth empowerment, and community development programs across Nigeria. Join us in making a difference.',
      keywords: 'NGO Nigeria, humanitarian aid, youth empowerment, orphan support, food distribution, community development',
      image: '/images/home-og.jpg',
    },
    about: {
      title: 'About Us - Our Mission & Vision',
      description: 'Learn about Hope for the Hopeless Initiative\'s mission, vision, core values, and our commitment to restoring hope and transforming lives across Nigeria.',
      keywords: 'NGO mission, charity organization, humanitarian values, community service Nigeria',
      image: '/images/about-og.jpg',
    },
    programs: {
      title: 'Our Programs - Making a Difference',
      description: 'Discover our comprehensive programs in Youth Development, Humanitarian Services, Family Welfare, and Sustainable Development.',
      keywords: 'youth programs Nigeria, humanitarian services, family welfare, sustainable development, community programs',
      image: '/images/programs-og.jpg',
    },
    successStories: {
      title: 'Success Stories - Lives Transformed',
      description: 'Read inspiring stories of individuals and families whose lives have been transformed through our programs and support.',
      keywords: 'impact stories, beneficiary stories, transformation stories, NGO success stories',
      image: '/images/stories-og.jpg',
    },
    gallery: {
      title: 'Gallery - Moments of Hope',
      description: 'View our photo gallery showcasing community outreach, food distribution, youth programs, and the lives we\'ve touched.',
      keywords: 'NGO gallery, humanitarian photos, community outreach pictures',
      image: '/images/gallery-og.jpg',
    },
    volunteer: {
      title: 'Volunteer - Join Our Mission',
      description: 'Make a difference by volunteering with Hope for the Hopeless Initiative. Opportunities in mentoring, food distribution, counseling, and more.',
      keywords: 'volunteer Nigeria, charity volunteer, community service, humanitarian volunteer',
      image: '/images/volunteer-og.jpg',
    },
    donate: {
      title: 'Donate - Support Our Cause',
      description: 'Your donation helps us provide food, education, healthcare, and hope to vulnerable individuals and families across Nigeria.',
      keywords: 'donate to charity, support NGO, humanitarian donation, sponsor a child',
      image: '/images/donate-og.jpg',
    },
    partners: {
      title: 'Our Partners - Collaborating for Impact',
      description: 'Meet our corporate, international, and local partners who help us create sustainable change in communities.',
      keywords: 'NGO partners, corporate partners, international collaboration, community partners',
      image: '/images/partners-og.jpg',
    },
    newsEvents: {
      title: 'News & Events - Stay Updated',
      description: 'Latest news, upcoming events, and announcements from Hope for the Hopeless Initiative.',
      keywords: 'NGO news, charity events, community announcements, humanitarian updates',
      image: '/images/news-og.jpg',
    },
    contact: {
      title: 'Contact Us - Get in Touch',
      description: 'Contact Hope for the Hopeless Initiative for inquiries, partnerships, or to learn how you can support our mission.',
      keywords: 'contact NGO, charity contact, humanitarian organization contact',
      image: '/images/contact-og.jpg',
    },
    privacy: {
      title: 'Privacy Policy',
      description: 'Read our privacy policy to understand how we collect, use, and protect your personal information.',
      keywords: 'privacy policy, data protection, NGO privacy',
      image: '/images/privacy-og.jpg',
    },
    terms: {
      title: 'Terms of Service',
      description: 'Terms and conditions for using the Hope for the Hopeless Initiative website and services.',
      keywords: 'terms of service, terms and conditions, website terms',
      image: '/images/terms-og.jpg',
    },
    cookies: {
      title: 'Cookie Policy',
      description: 'Learn about how we use cookies to improve your browsing experience on our website.',
      keywords: 'cookie policy, website cookies, privacy settings',
      image: '/images/cookies-og.jpg',
    },
    programDetail: {
      title: 'Program Details - ',
      description: 'Learn more about our programs and how they make a difference in communities across Nigeria.',
      keywords: 'program details, humanitarian programs, community initiatives',
      image: '/images/program-detail-og.jpg',
    },
    storyDetail: {
      title: 'Success Story - ',
      description: 'Read inspiring transformation stories from our beneficiaries.',
      keywords: 'success story, beneficiary story, transformation story',
      image: '/images/story-detail-og.jpg',
    },
    eventDetail: {
      title: 'Event Details - ',
      description: 'Get all the details about our upcoming events and news announcements.',
      keywords: 'event details, NGO event, community event',
      image: '/images/event-detail-og.jpg',
    },
  },
}